jakemmarsh/angularjs-gulp-browserify-boilerplate

gulp/config.js
gulp/tasks/browserify.js
package.json

Source maps are generated by default with `gulp prod`. They can be disabled
by setting `config.browserify.sourcemap` to false.

Add source map support.

---

README.md
gulp/config.js
gulp/tasks/gzip.js
gulp/tasks/production.js
package.json

Pre-compress assets with gzip, so that web server can serve without compressing.
Adds `gzip` task to `gulp prod`. See
http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html and
http://www.lemoda.net/mod_rewrite/gzip-static/index.html

Pre-compress assets with gzip

---

package.json

Hi there,
Nice work with this boilerplate, everything runs smoothly. Got my project running in minutes.
However, I wanted to introduce Bourbon & Neat for styling http://bourbon.io/. And, they seem to use new Sass declarations (Sass ^3.3.0), which are only supported in the newer versions of Libsass, which is packaged into gulp-sass (node-sass, to be specific). So I've updated 0.7.3 to 1.3.3. Everything bourbon-based compiles on my machine.

Update gulp-sass to support new Libsass

---

gulp/tasks/fonts.js

The Gulp `font` task was missing a require, this adds it in.

Add missing require

---

app/js/controllers/_index.js
app/js/directives/_index.js
app/js/services/_index.js
gulp/tasks/browserify.js
package.json
test/karma.conf.js

Hey!
To start with, thank you for your work on this seed project. I used it a few months ago to get comfortable with Browserify, and it was a great jumping point.
This PR eliminates a "moving part" in the app (manually adding to the `_index.js` files). I've added bulk-require, and the bulkify transform (written by Substack).
Now, if you add any non-test JS files to the controllers/directives/services directories, they'll automatically be require()'d when someone require()'s your `_index.js` file.

Implement bulk-require, to make _index.js files less work to maintain

---

app/js/directives/example.js

PR changes `$scope` to `scope`, and `$element` to `element` in the example directive, to make it clearer that they are positional parameters, rather than being injected by Angular's DI mechanism.
https://thinkster.io/egghead/scope-vs-scope
http://www.bennadel.com/blog/2716-when-to-use-scope-vs-scope-in-angularjs.htm

Remove $ from non-injected, positional arguments in example directive

---

package.json
test/karma.conf.js

This PR updates `angular`, `angular-mocks`, and `angular-ui-router` to their latest stable versions.
It also removes `browserify-shim`, which is no longer necessary since the [*instantaneous-browserification*](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1314-instantaneous-browserification-2015-02-24) release of AngularJS, which now packages it as a CommonJS module (hooray!).

Upgrade to the latest angular, and drop browserify-shim

---

README.md
app/js/main.js
app/js/on_config.js

I think it's a little cleaner to rename the config phase into a some more descriptive filename. I changed this at all of my project to avoid misunderstandings. And in this file there aren't routes only.
What do you think?

Renaming routes.js into on_config.js because it's the config phase

---

gulp/tasks/browserSync.js

Missing comma prevents browser sync startup when running gulp dev

Fix browserSync syntax

---

test/karma.conf.js

There is the following warning when I run ```gulp unit```.
```
Chrome 44.0.2403 (Linux 0.0.0) LOG: 'WARNING: Tried to load angular more than once.'
```
Because angular is already included in the main script, I removed the one from node_modules.

Remove the extra angular declaration from tests

---

gulp/tasks/browserify.js
gulp/tasks/styles.js

When building for production:
- disable CSS sourceComments
- generate CSS sourcemap file: main.css.map

Fix CSS sourcemaps for production

---

gulp/config.js
gulp/tasks/styles.js

Added the possibility to add Sass' `includePaths` via gulp/conf.js

Added Sass include paths to gulp configuration

---

gulp/tasks/browserify.js

Just throwing this out there as some users might require some tweaking for whatever reason.
This could be extended to be declared in the config and have separate options for dev/prod
here's an example if a user wanted babel to ignore scripts in the bower_components directory:
```{ 'name':babelify, 'options':{'ignore':['bower_components']}}```

Added transform options to browserify gulp task

---

package.json
test/protractor.conf.js

Testing scripts were not working at all and these changes make them work again. 
The NPM scripts were referencing themselves and falling into a loop or referencing old bin files (*update-webdriver* for example). Also the test port was all wrong for protractor, it was using the *BrowserSync* one.

Fix testing scripts

---

gulp/config.js
gulp/tasks/browserSync.js

I was losing my sanity thinking I broke something after merging all the es6 changes lol.
one of the regressions was browserSync checking to see if an assets extensions was whitelisted in a predefined array. Unfortunately some fonts use somefont.tff?v1.2.4 as their name to prevent caching.
With the logic of splitting every occurrence of a period you'd get an array [somefont, ttf?v1, 2, 4] which would fail even if you explicitly added ttf to that array. 
I was going to add a regex to search for the extension but then I thought what's the point of this? why not just allow anything that has an extension? as everything routed through angular uses a directory structure. And anything with a '.' is probably an asset.
If someone wants to use /myapp.dev/ then I guess a regex would be needed. …

Fix not being able to serve fonts and other assets using query string cache busters.

---

gulp/tasks/production.js
package.json

#110 brought up an issue with a race condition occurring when the `views` task takes too long, meaning `browserify` was run before `templates.js` was created. This should fix that issue

ensure all asset tasks are done before browserify

---

gulp/tasks/browserify.js

In master currently, `debug` is always set to `true` for Browserify. This tells Browserify to create an inline sourcemap for the bundle. However, this is additional (unnecessary) work when the prod task is running, since Uglify will strip the source maps anyway.
Further, in local development, this was actually breaking sourcemaps. The reason is because the current Browserify configuration places the sourcemap inline (`debug = true`). However, `gulp-sourcemaps` is being instructed to use an external sourcemap file. Since the internal sourcemaps exists from the initial build, the browser will not fetch the external sourcemap created by the `rebundle` function.
The following behavior should be seen after merging this PR:
1. Sourcemaps will always be inline
2. Sourcemaps will be generated …

Fix sourcemaps for Browserify

---

gulp/tasks/browserify.js
gulp/tasks/fonts.js
gulp/tasks/images.js
gulp/tasks/styles.js
gulp/tasks/views.js

This solves #108.
To test it you can add a bunch of CSS to the main.scss file (for example, the Bootstrap source file) and then trying to do a simple `body { background: red; }` change. When there's a lot of CSS code, the sync doesn't work too well. By removing `{ once: true }` the changes not only work, but they are smarter.

Remove {once: true} from browserSync.stream

---

README.md

Makes it a bit easier to keep an eye on outdated deps.

Add Badge to display devDep status on repo, with link to details

---

gulp/tasks/clean.js
package.json

Returning the promise from the task now, rather than taking in a done cb - both work as async hints to gulp

Update "del" dep to latest version

---

app/js/controllers/index.js
app/js/directives/index.js
app/js/filters/index.js
app/js/services/index.js

In `app/js/controllers/index.js`, our code as below:
```javascript
const controllers = bulk(__dirname, ['./**/!(*index|*.spec).js']);
Object.keys(controllers).forEach((key) => {
let item = controllers[key];
controllersModule.controller(item.name, item.fn);
});
```
If we have a file structure looks like below:
```
-- controllers
-- example.js
-- folder
-- another.js
```
We got a `controllers` object after bulked:
```json
{
"example": {
"fn": "ExampleCtrl()",
"name": "ExampleCtrl"
},
"folder": {
"another": {
"fn": "AnotherCtrl()",
"name": "AnotherCtrl"
}
}
}
```
Unfortunately, `AnotherCtrl` did not declare as a controller because it's lying under a folder. `services`/`filters`/`directives` have the same problem, so I create this PR to solve it.

Recursively include submodules

---

gulp/tasks/development.js

When view is too large and browserify runs faster than that.
template.js wouldn't be available for browserify to import i
So, gulp dev would get compile error that template.js not found.
browserify should be run after all other dependencies are satisfied.

Fixed gulp dev issue at first run

---

gulp/tasks/styles.js

The autoprefixer plugin is only taking into account the first argument ('last 2 versions')
The correct syntax should be:
`autoprefixer({
browsers: [ ... ]
});
`

Fix autoprefixer step

---

gulp/config.js
gulp/index.js
gulp/tasks/browserSync.js
gulp/tasks/browserify.js
gulp/tasks/clean.js
gulp/tasks/deploy.js
gulp/tasks/development.js
gulp/tasks/eslint.js
gulp/tasks/fonts.js
gulp/tasks/gzip.js
gulp/tasks/images.js
gulp/tasks/production.js
gulp/tasks/protractor.js
gulp/tasks/styles.js
gulp/tasks/test.js
gulp/tasks/unit.js
gulp/tasks/views.js
gulp/tasks/watch.js
gulp/util/bundleLogger.js
gulp/util/handleErrors.js
gulp/util/scriptFilter.js
gulp/util/testServer.js
test/e2e/example_spec.js
test/e2e/routes_spec.js
test/karma.conf.js
test/unit/constants_spec.js
test/unit/controllers/example_spec.js
test/unit/directives/example_spec.js
test/unit/filters/example_spec.js
test/unit/services/example_spec.js

Removed useless "use strict" from tasks and tests, [es6 has strict mode enabled by default](http://stackoverflow.com/a/31685340/3741361).
I tested it by declaring a variable globally with no prefix and it behaves as it would in strict mode.

Removed redundant 'use strict' since it comes standard with es6
